### ISSUE TITLE
Alternative data?

### ISSUE THREAD

**Issue by biomrpaul** [mathieu-lemire/celluloid_0.11#1]
Hi Mathieu,

I was wondering if CELLULOID could be run on low-pass/shallow WGS and/or WES data?

Thanks,
Matt Paul

**Comment by mathieu-lemire** [comment]
For low coverage WGS, the problem reside in the low read counts at het positions. To ignore allelic ratios, you can check the singleCelluloid branches (on both source code and tutorial) that I wrote for single cell sequencing experiment.  Check tutorial file names related to the xonly option.   I can't comment on WES.

**Comment by biomrpaul** [comment]
Ok that makes sense. Thanks!
